### ISSUE TITLE
Thay đổi phần giao thức UART để giảm lượng data gửi đi và thêm phần cho câu lệnh điều khiển từ găng tay

### ISSUE THREAD

**Issue by hieutranngoc-itr** [TNH510/5_DOF_Robot_Arm#129]
- [x] Thiết kế giao thức UART gồm 3 giá trị vị trí (3 * 3), câu lệnh 1 byte, 1 byte CRC-ATM: 
[**x_3**][**x_2**][**x_1**][**y_3**][**y_2**][**y_1**][**z_3**][**z_2**][**z_1**][**CMD**][**CRC-ATM**]
- Thuật toán **CRC8-ATM** 
```
static uint8_t lc709204f_calculate_crc_8_atm(uint8_t *data, uint16_t length)
{
  assert(data != NULL);

  uint8_t crc = 0;
  for (uint16_t i = 0; i < length; i++)
  {
    crc ^= data[i];

    for (uint8_t bit = 0; bit < 8; bit++)
    {
      if (crc & 0x80)
      {
        crc = (crc << 1) ^ 0x07;
      }
      else
      {
        crc <<= 1;
      }
    }
  }

  return crc;
}
```

**Comment by hieutranngoc-itr** [comment]
@Thachhcmute3001 

![Image](https://github.com/TNH510/5_DOF_Robot_Arm/assets/145527330/79df3a96-0d5f-4575-96fb-a8ca8b05ac56)

**Comment by Thachhcmute3001** [comment]
Acknowledged

**Comment by hieutranngoc-itr** [comment]
![Image](https://github.com/TNH510/5_DOF_Robot_Arm/assets/145527330/c5cdc429-390a-4a90-a80c-777a3967048f)

**Comment by hieutranngoc-itr** [comment]
https://github.com/TNH510/Internet-of-Things @Thachhcmute3001

**Comment by hieutranngoc-itr** [comment]
- [x] Debug cách tối ưu tốc độ truyền từ module UART
- [ ] Test truyền nhận UART trên module HC-12
- [x] Test và thêm phần điều khiển vận tốc dùng Jacobi nghịch

**Comment by Thachhcmute3001** [comment]
:)) oh noo

**Comment by hieutranngoc-itr** [comment]
@Thachhcmute3001 Yeah, you look very awake 😃
