### ISSUE TITLE
Nghiên cứu, tìm các nguồn nghiên cứu có liên quan đến găng tay robot

### ISSUE THREAD

**Issue by TNH510** [TNH510/5_DOF_Robot_Arm#22]
https://www.slideshare.net/man2017/thit-k-h-thng-iu-khin-m-phng-chuyn-ng-cnh-taypdf
https://www.researchgate.net/publication/333335847_Semi-Autonomous_Robot_Teleoperation_With_Obstacle_Avoidance_via_Model_Predictive_Control

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7309037/
https://x-io.co.uk/open-source-imu-and-ahrs-algorithms/

https://www.youtube.com/watch?v=5HuN9iL-zxU
Lọc nhiễu Kanman: https://kdientu.duytan.edu.vn/media/133474/bo-loc-kalman.pdf

**Comment by hieutranngoc-itr** [comment]
- [x] Lấy được data từ 3 cảm biến và vẽ trên 1 script python để tiện quan sát cũng như áp dụng lọc nhiễu
- [x] Thêm phần truyền nhận COM trên giao diện C# điều khiển chính và test truyền nhận okela
- [x] Tiến hành truyền góc giả lập để điều khiển robot mô phỏng
- [x] Tiến hành lấy góc thực tế từ cảm biến và điều khiển robot mô phỏng
