### ISSUE TITLE
Hoàn thiện file báo cáo đồ án (Format, các nội dung chém gió)

### ISSUE THREAD

**Issue by hieutranngoc-itr** [TNH510/5_DOF_Robot_Arm#50]

**Comment by TNH510** [comment]
CHƯƠNG 2: CƠ SỞ LÝ THUYẾT
- [ ] Cơ sở lý thuyết về công nghệ
  - Các công nghệ và tính năng được ứng dụng trong robot bốc xếp
- [ ] Cơ sở lý thuyết về cơ khí
  - Cấu hình của robot
  - Các loại đầu tay gắp
- [ ] Cơ sở lý thuyết về điện điện tử
  - Hệ thống điều khiển bằng PLC cùng driver
- [ ] Cơ sở lý thuyết về lập trình giao diện
  - Lập trình giao diện trên máy tính

CHƯƠNG 3: NGHIÊN CỨU ĐỘNG HỌC VÀ ĐỘNG LỰC HỌC TAY MÁY
- [ ] Tính toán 
    +	Tính toán động học thuận vị trí
    +	Tính toán động học nghịch vị trí
    +	Tính toán động lực học
- [ ] Mô phỏng MATLAB
    +	Xây dựng mô hình robot trên Simulink
    +	Mô phỏng vị trí dựa trên kết quả tính toán
CHƯƠNG 4: NGHIÊN CỨU, PHÁT TRIỂN THIẾT KẾ CƠ KHÍ
- [ ] Nghiên cứu cơ khí phần cánh tay robot
    +	Cấu tạo cơ khí của các khâu
    +	Các bộ truyền và thông số
    +	Thông số động cơ và công suất
- [ ] Phát triển phần đầu tay gắp cho cánh tay robot
    +	Các yêu cầu của đầu tay gắp
    +	Chọn loại cơ cấu cho tay gắp
    +	Tính toán lực và chọn động cơ (Vẽ biểu đồ lực và vị trí)
CHƯƠNG 5: THIẾT KẾ HỆ THỐNG ĐIỀU KHIỂN
- [ ] Thiết kế hệ thống điện
+	Hệ thống điện điều khiển (bản vẽ, giải thích)
- [ ] Thiết kế giải thuật điều khiển khiển
+	Các câu lệnh điều khiển
    +	Set Home
    +	Go Home
    +	Chạy JOG
    +	Chạy đơn điểm (MoveJ)
    +	Chạy đa điểm (MoveL, MoveC)
CHƯƠNG 6: THIẾT KẾ ỨNG DỤNG GIÁM SÁT VÀ ĐIỀU KHIỂN
- [ ] Thiết kế giao diện điều khiển bằng C#
    +	Tổng quan giao diện chính
    +	Kết nối với PLC từ máy tính
    +	Đọc giá trị góc trả về từ PLC
    +	Gửi câu lệnh điều khiển xuống PLC
    +	Kết nối với MATLAB để thực hiện xử lí dữ liệu góc
- [ ] Thiết kế giao diện giám sát bằng MATLAB
    +	Tổng quan về giao diện giám sát trên MATLAB
    +	Giao thức truyền và nhận thông tin từ C#
    +	Thể hiện hình dáng robot thực tế theo thời gian thực
    +	Vẽ đồ thị vị trí các góc, vị trí khâu chấp hành cuối và hỗ trợ xuất file data
CHƯƠNG 7: THI CÔNG, THỰC NGHIỆM VÀ PHÂN TÍCH KẾT QUẢ
- [ ] Thi công cơ khí
    +	Mô hình cơ khí thực tế của cánh tay robot
    +	Mô hình cơ khí thực tế của đầu tay gắp
- [ ] Thi công hệ thống điện
    +	Kết quả chụp hệ thống điện và set up khi kết nối với máy tính
- [ ] Thi công ứng dụng điều khiển
    +	Kết quả chạy thực tế của giao diện điều khiển và giám sát
- [ ] Thực nghiệm chạy robot
    +	Thiết kế hành trình chạy thực nghiệm
    +	Kết quả chạy thu được từ thực tế và trên giao diện giám sát
- [ ] Phân tích kết quả
    +	Về độ chính xác
    +	Về thời gian đáp ứng
    +	Về tính ổn định của hệ thống điều khiển và giám sát
CHƯƠNG 8: KẾT LUẬN
- [ ] Các vấn đề đã đạt được
- [ ] Các hạn chế của hệ thống
- [ ] Các giải pháp và hướng phát triển trong tương lai
